services:
  - type: web
    name: tayaria-warranty-be
    env: go
    plan: free
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: APP_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: STORAGE_BUCKET
        sync: false 